version: 2
updates:
  # Keep npm dependencies up to date
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 5
    labels:
      - dependencies
    groups:
      minor-and-patch:
        applies-to: version-updates
        update-types:
          - minor
          - patch
      dev-deps:
        applies-to: version-updates
        dependency-type: development
        patterns:
          - "*"

  # Keep GitHub Actions up to date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:30"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 3
    labels:
      - dependencies
      - github-actions
