area/docs:
  - changed-files:
      - any-glob-to-any-file:
          - 'docs/**'
area/tests:
  - changed-files:
      - any-glob-to-any-file:
          - 'test/**'
area/build:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/workflows/**'
          - 'Dockerfile*'
area/code:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/**'
