/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.auth-limiter.jsonc --include-runtime=false --env-interface=GeneratedAuthLimiterEnv src/worker-env/auth-limiter-env.d.ts` (hash: fbfac0463348110025886069aadb5555)
interface __BaseEnv_GeneratedAuthLimiterEnv {
  MCP_CF_STRUCTURED_LOGS_ENABLED: 'true';
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('../worker-auth-limiter');
    durableNamespaces: 'AuthFailureLimiterDO';
  }
  interface Env extends __BaseEnv_GeneratedAuthLimiterEnv {}
}
interface GeneratedAuthLimiterEnv extends __BaseEnv_GeneratedAuthLimiterEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<Cloudflare.Env, 'MCP_CF_STRUCTURED_LOGS_ENABLED'>
  > {}
}
