/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.edge.jsonc --include-runtime=false --env-interface=GeneratedEdgeEnv src/worker-env/edge-env.d.ts` (hash: 4bebb9e206151032d74ee98846429090)
interface __BaseEnv_GeneratedEdgeEnv {
  OAUTH_KV: KVNamespace;
  ANALYTICS: AnalyticsEngineDataset;
  SPA_ASSETS: Fetcher;
  MCP_UI_SESSION_BOOTSTRAP_RATE_LIMIT_MAX: '20';
  MCP_UI_SESSION_BOOTSTRAP_RATE_LIMIT_WINDOW_SECONDS: '60';
  MCP_UI_SESSION_BOOTSTRAP_RATE_LIMIT_BLOCK_SECONDS: '300';
  MCP_BOUNDARY_FAIL_OPEN: 'false';
  CODEMODE_ENABLED: 'false';
  MCP_OAUTH_REGISTRATION_TOKEN_TTL_SECONDS: '3600';
  MCP_CF_ANALYTICS_ENABLED: 'true';
  MCP_CF_STRUCTURED_LOGS_ENABLED: 'true';
  AUTH_FAILURE_LIMITER: DurableObjectNamespace /* AuthFailureLimiterDO from courtlistener-mcp-auth-limiter */;
  MCP_SERVICE: Fetcher /* courtlistener-mcp-mcp */;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('../worker-edge');
  }
  interface Env extends __BaseEnv_GeneratedEdgeEnv {}
}
interface GeneratedEdgeEnv extends __BaseEnv_GeneratedEdgeEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<
      Cloudflare.Env,
      | 'MCP_UI_SESSION_BOOTSTRAP_RATE_LIMIT_MAX'
      | 'MCP_UI_SESSION_BOOTSTRAP_RATE_LIMIT_WINDOW_SECONDS'
      | 'MCP_UI_SESSION_BOOTSTRAP_RATE_LIMIT_BLOCK_SECONDS'
      | 'MCP_BOUNDARY_FAIL_OPEN'
      | 'CODEMODE_ENABLED'
      | 'MCP_OAUTH_REGISTRATION_TOKEN_TTL_SECONDS'
      | 'MCP_CF_ANALYTICS_ENABLED'
      | 'MCP_CF_STRUCTURED_LOGS_ENABLED'
    >
  > {}
}
