/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.mcp.jsonc --include-runtime=false --env-interface=GeneratedMcpEnv src/worker-env/mcp-env.d.ts` (hash: 96d8adf66656a0115a37a8ea121916cd)
interface __BaseEnv_GeneratedMcpEnv {
  ASYNC_JOBS_KV: KVNamespace;
  ANALYTICS: AnalyticsEngineDataset;
  ASYNC_TOOL_QUEUE: Queue;
  AI: Ai;
  MCP_BOUNDARY_FAIL_OPEN: 'false';
  CODEMODE_ENABLED: 'false';
  MCP_ASYNC_QUEUE_ENABLED: 'false';
  MCP_CF_ANALYTICS_ENABLED: 'true';
  MCP_CF_STRUCTURED_LOGS_ENABLED: 'true';
  AUTH_FAILURE_LIMITER: DurableObjectNamespace /* AuthFailureLimiterDO from courtlistener-mcp-auth-limiter */;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('../worker-mcp');
  }
  interface Env extends __BaseEnv_GeneratedMcpEnv {}
}
interface GeneratedMcpEnv extends __BaseEnv_GeneratedMcpEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<
      Cloudflare.Env,
      | 'MCP_BOUNDARY_FAIL_OPEN'
      | 'CODEMODE_ENABLED'
      | 'MCP_ASYNC_QUEUE_ENABLED'
      | 'MCP_CF_ANALYTICS_ENABLED'
      | 'MCP_CF_STRUCTURED_LOGS_ENABLED'
    >
  > {}
}
