name: Auto Assign Reviewers

on:
  pull_request_target:
    types: [opened, ready_for_review]

permissions:
  contents: read
  pull-requests: write

jobs:
  add-reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Request reviewers via API
        uses: actions/github-script@v8
        with:
          script: |
            const reviewers = ['blakeox'];
            const pr = context.payload.pull_request;
            if (!pr) {
              core.info('No pull_request payload found.');
              return;
            }
            const title = pr.title || '';
            const isDraft = pr.draft || /\b(wip|draft)\b/i.test(title);
            if (isDraft) {
              core.info('PR is draft/WIP. Skipping requesting reviewers.');
              return;
            }
            await github.rest.pulls.requestReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr.number,
              reviewers
            });
