name: Sync Labels

on:
  push:
    branches: [main]
    paths:
      - .github/labels.yml
  workflow_dispatch: {}

permissions:
  contents: read
  issues: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Sync labels
        uses: crazy-max/ghaction-github-labeler@v5
        with:
          dry-run: false
          skip-delete: true
          yaml-file: .github/labels.yml
