name: Sync Labels

on:
  push:
    branches: [main]
    paths:
      - .github/labels.yml
  workflow_dispatch: {}

permissions:
  contents: read
  issues: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - name: Sync labels
        uses: crazy-max/ghaction-github-labeler@548a7c3603594ec17c819e1239f281a3b801ab4d # v6.0.0
        with:
          dry-run: false
          skip-delete: true
          yaml-file: .github/labels.yml
